name: seed
version: 1.0
author: xNagisa_
main: info.icodethings.seed.Main
load: startup
commands:
  generate:
    description: Generate a block of perlin terrain
    usage: /generate <width int> <height int> <freq double> <octaves int> <persistance double> <lacunarity double> <scale int> <seed int>